name: Release
run-name: Release triggered by ${{ github.actor }}
on:
  # push:
  #     tags:
  #     - "v**"
  - workflow_dispatch
  - workflow_call
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: rebornos/rebornos:latest
      ports:
        - 80
      # options: --privileged
    steps:
      - id: init_docker_step
        name: Initialize RebornOS Docker Container        
        run: sh /usr/bin/init-rebornos-docker.sh
      - id: checkout_repository_step
        name: Checkout Git Repository
        uses: actions/checkout@v3
      - id: build_package_step
        name: Build Package
        run: |
          chown -R rebornos packaging
          chmod -R +x packaging
          sudo -u rebornos sh -c "packaging/build_package.sh stable --noconfirm"
      - id: upload_package_step
        name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with: 
          name: Stable Package
          path: packaging/${{ github.event.repository.name }}/${{ github.event.repository.name }}*.pkg.tar.*
          if-no-files-found: error
  release:  
    needs: build        
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: download_package_step 
        name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: Stable Package
      - name: Display structure of downloaded files
        run: ls -R
  
